//
//  UIButton+TitleColor.h
//  UIButton+TitleColor
//
//  Copyright (c) 2015 Draveness. All rights reserved.
//
//  These files are generated by ruby script, if you want to modify code
//  in this file, you are supposed to update the ruby code, run it and 
//  test it. And finally open a pull request.

#import <UIKit/UIKit.h>
#import "UIView+NightVersion.h"

@interface UIButton (TitleColor)

/**
 * Set this property when switch to night version uibutton TitleColor turns to this color.
 */
@property (nonatomic, strong) IBInspectable UIColor *nightTColorN;
@property (nonatomic, strong) IBInspectable UIColor *nightTColorH;
@property (nonatomic, strong) IBInspectable UIColor *nightTColorS;
@property (nonatomic, strong) IBInspectable UIColor *nightTColorD;

/**
 *  UIButton TitleColor in normal version.
 */
@property (nonatomic, strong, readonly) UIColor *normalTitleColorN;
@property (nonatomic, strong, readonly) UIColor *normalTitleColorH;
@property (nonatomic, strong, readonly) UIColor *normalTitleColorS;
@property (nonatomic, strong, readonly) UIColor *normalTitleColorD;

@property (nonatomic, strong) IBInspectable UIImage *nightImageN;
@property (nonatomic, strong) IBInspectable UIImage *nightImageH;
@property (nonatomic, strong) IBInspectable UIImage *nightImageS;
@property (nonatomic, strong) IBInspectable UIImage *nightImageD;

@property (nonatomic, strong, readonly) UIImage *normalImageN;
@property (nonatomic, strong, readonly) UIImage *normalImageH;
@property (nonatomic, strong, readonly) UIImage *normalImageS;
@property (nonatomic, strong, readonly) UIImage *normalImageD;

@property (nonatomic, strong) IBInspectable UIImage *nightBackImageN;
@property (nonatomic, strong) IBInspectable UIImage *nightBackImageH;
@property (nonatomic, strong) IBInspectable UIImage *nightBackImageS;
@property (nonatomic, strong) IBInspectable UIImage *nightBackImageD;

@property (nonatomic, strong, readonly) UIImage *normalBackImageN;
@property (nonatomic, strong, readonly) UIImage *normalBackImageH;
@property (nonatomic, strong, readonly) UIImage *normalBackImageS;
@property (nonatomic, strong, readonly) UIImage *normalBackImageD;

@end
